const loadingKeys = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  UNIQUE: "UNIQUE",
  SAVE_SUDOKU: "SAVE_SUDOKU",
  GET_ALL_SUDOKU: "GET_ALL_SUDOKU",
  GET_USER_SUDOKU: "GET_USER_SUDOKU",
  PUBLISH_SUDOKU: "PUBLISH_SUDOKU",
  GET_SUDOKU_BY_ID: "GET_SUDOKU_BY_ID",
  DELETE_SUDOKU: "DELETE_SUDOKU",
  SAVE_SOLVED_SUDOKU: "SAVE_SOLVED_SUDOKU",
  CHECK_ALREADY_SOLVED: "CHECK_ALREADY_SOLVED",
};

export default loadingKeys;
